using System.Text;
using System.Web.Mvc;

using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;

namespace RazorGenerator.SourceGeneration.Tests;

public class CSharpSourceGeneratorTest<TSourceGenerator> : CSharpSourceGeneratorTest<TSourceGenerator, DefaultVerifier>
	where TSourceGenerator : new()
{

}

public class Tests
{
	private static readonly ReferenceAssemblies SystemWebMvc = ReferenceAssemblies.NetFramework.Net48.Default
		.AddAssemblies(["System.Web"])
		//.AddAssemblies(["System.Web", "System.Web.Mvc", "System.Web.Razor", "System.Web.Helpers", "System.Web.WebPages.Deployment", "System.Web.WebPages", "System.Web.WebPages.Razor", "Microsoft.Web.Infrastructure"]);
		.AddPackages([
			new("Microsoft.CSharp", "4.7.0"),
			new("Antlr", "3.5.0.2"),
			new("Microsoft.AspNet.Mvc", "5.2.9"),
			new("Microsoft.AspNet.Web.Optimization", "1.1.3"),
			new("Microsoft.AspNet.WebApi", "5.2.9"),
			new("Microsoft.Web.LibraryManager.Build", "2.1.175"),
			new("Newtonsoft.Json", "13.0.1"),
			new("WebGrease", "1.6.0"),
		]);

	[Test]
	public async Task First(CancellationToken cancellationToken = default)
	{
		const string Input = """
			<main>
			    <h1>Hello World!</h1>
			    <section class="row" aria-labelledby="aspnetTitle">
			        <h1 id="aspnetTitle">ASP.NET</h1>
			        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
			        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
			    </section>
			    <div class="row">
			        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
			            <h2 id="gettingStartedTitle">Getting started</h2>
			            <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
			            a broad range of clients, including browsers and mobile devices. ASP.NET Web API
			            is an ideal platform for building RESTful applications on the .NET Framework.</p>
			            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
			        </section>
			        <section class="col-md-4" aria-labelledby="librariesTitle">
			            <h2 id="librariesTitle">Get more libraries</h2>
			            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
			            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
			        </section>
			        <section class="col-md-4" aria-labelledby="hostingTitle">
			            <h2 id="hostingTitle">Web Hosting</h2>
			            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
			            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
			        </section>>
			    </div>
			</main>
			""";
		const string Output = $$"""
			//------------------------------------------------------------------------------
			// <auto-generated>
			//     This code was generated by a tool.
			//     Runtime Version:{{"8.0.25"}}
			//
			//     Changes to this file may cause incorrect behavior and will be lost if
			//     the code is regenerated.
			// </auto-generated>
			//------------------------------------------------------------------------------

			namespace ASP
			{
				using System;
				using System.Collections.Generic;
				using System.IO;
				using System.Linq;
				using System.Net;
				using System.Web;
				using System.Web.Helpers;
				using System.Web.Security;
				using System.Web.UI;
				using System.Web.WebPages;
				
				[System.Runtime.CompilerServices.CompilerGenerated()]
				[System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
				public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
				{
					protected System.Web.HttpApplication ApplicationInstance
					{
						get
						{
							return ((System.Web.HttpApplication)(Context.ApplicationInstance));
						}
					}
			#line hidden
					public override void Execute()
					{
			WriteLiteral("<main>\r\n    <h1>Hello World!</h1>\r\n    <section class=\"row\" aria-labelledby=\"aspn" +
			"etTitle\">\r\n        <h1 id=\"aspnetTitle\">ASP.NET</h1>\r\n        <p class=\"lead\">AS" +
			"P.NET is a free web framework for building great Web sites and Web applications " +
			"using HTML, CSS, and JavaScript.</p>\r\n        <p><a href=\"https://asp.net\" class" +
			"=\"btn btn-primary btn-md\">Learn more &raquo;</a></p>\r\n    </section>\r\n    <div c" +
			"lass=\"row\">\r\n        <section class=\"col-md-4\" aria-labelledby=\"gettingStartedTi" +
			"tle\">\r\n            <h2 id=\"gettingStartedTitle\">Getting started</h2>\r\n          " +
			"  <p>ASP.NET Web API is a framework that makes it easy to build HTTP services th" +
			"at reach\r\n            a broad range of clients, including browsers and mobile de" +
			"vices. ASP.NET Web API\r\n            is an ideal platform for building RESTful ap" +
			"plications on the .NET Framework.</p>\r\n            <p><a class=\"btn btn-outline-" +
			"dark\" href=\"https://go.microsoft.com/fwlink/?LinkId=301870\">Learn more &raquo;</" +
			"a></p>\r\n        </section>\r\n        <section class=\"col-md-4\" aria-labelledby=\"l" +
			"ibrariesTitle\">\r\n            <h2 id=\"librariesTitle\">Get more libraries</h2>\r\n  " +
			"          <p>NuGet is a free Visual Studio extension that makes it easy to add, " +
			"remove, and update libraries and tools in Visual Studio projects.</p>\r\n         " +
			"   <p><a class=\"btn btn-outline-dark\" href=\"https://go.microsoft.com/fwlink/?Lin" +
			"kId=301871\">Learn more &raquo;</a></p>\r\n        </section>\r\n        <section cla" +
			"ss=\"col-md-4\" aria-labelledby=\"hostingTitle\">\r\n            <h2 id=\"hostingTitle\"" +
			">Web Hosting</h2>\r\n            <p>You can easily find a web hosting company that" +
			" offers the right mix of features and price for your applications.</p>\r\n        " +
			"    <p><a class=\"btn btn-outline-dark\" href=\"https://go.microsoft.com/fwlink/?Li" +
			"nkId=301872\">Learn more &raquo;</a></p>\r\n        </section>>\r\n    </div>\r\n</main" +
			">");

					}
					public _Page_Views_Home_Index_cshtml()
					{
					}
				}
			}

			""";
		var test = new CSharpSourceGeneratorTest<LegacyRazorGenerator>()
		{
			ReferenceAssemblies = SystemWebMvc,
			TestState =
			{
				AdditionalFiles =
				{
					("Views/Home/Index.cshtml", Input)
				},
				GeneratedSources =
				{
					(typeof(LegacyRazorGenerator), "Views/Home/Index.cshtml.g.cs", SourceText.From(Output, Encoding.UTF8, SourceHashAlgorithm.Sha256)),
				},
			},
		};

		await test.RunAsync(cancellationToken);
	}
}

//public class Tests
//{
//	[Test]
//	public void Basic()
//	{
//		Console.WriteLine("This is a basic test");
//	}

//	[Test]
//	[Arguments(1, 2, 3)]
//	[Arguments(2, 3, 5)]
//	public async Task DataDrivenArguments(int a, int b, int c)
//	{
//		Console.WriteLine("This one can accept arguments from an attribute");

//		var result = a + b;

//		await Assert.That(result).IsEqualTo(c);
//	}

//	[Test]
//	[MethodDataSource(nameof(DataSource))]
//	public async Task MethodDataSource(int a, int b, int c)
//	{
//		Console.WriteLine("This one can accept arguments from a method");

//		var result = a + b;

//		await Assert.That(result).IsEqualTo(c);
//	}

//	[Test]
//	[ClassDataSource<DataClass>]
//	[ClassDataSource<DataClass>(Shared = SharedType.PerClass)]
//	[ClassDataSource<DataClass>(Shared = SharedType.PerAssembly)]
//	[ClassDataSource<DataClass>(Shared = SharedType.PerTestSession)]
//	public void ClassDataSource(DataClass dataClass)
//	{
//		Console.WriteLine("This test can accept a class, which can also be pre-initialised before being injected in");

//		Console.WriteLine("These can also be shared among other tests, or new'd up each time, by using the `Shared` property on the attribute");
//	}

//	[Test]
//	[DataGenerator]
//	public async Task CustomDataGenerator(int a, int b, int c)
//	{
//		Console.WriteLine("You can even define your own custom data generators");

//		var result = a + b;

//		await Assert.That(result).IsEqualTo(c);
//	}

//	public static IEnumerable<(int a, int b, int c)> DataSource()
//	{
//		yield return (1, 1, 2);
//		yield return (2, 1, 3);
//		yield return (3, 1, 4);
//	}
//}
